#!/usr/bin/env python3

# Activity Metrics (acme)
# Copyright (C) 2024 Ray Mentose. 
# Latest source can be found at: https://github.com/ryt/activity-metrics.git


v = '0.2.1'
c = 'Copyright (C) 2024 Ray Mentose.'
man = """
Activity Metrics: A tool to analyze & display personal activity statistics.
Copyright (C) 2024 Ray Mentose. Latest source: https://github.com/ryt/activity-metrics

Usage:

  Show log file statistics and list all found log files.
  ------------------------------------------------------
  Run       Command
  -------------------------
  ame       
  acme      (stats|-s)
  acme      (list-files|-l)


  Analyze entries for a specific date or today.
  ---------------------------------------------
  Run       Date
  ------------------------------------------
  acme      {date_input}
  acme      (M/D|M-D)
  acme      (Y-M-D|Y/M/D)
  acme      (M-D-Y|M/D/Y)
  acme      (today|tod|-t|yesterday|yest|-y)


  Generate a timesheet CSV file for a specific date. Create columns with categorize.
  ----------------------------------------------------------------------------------
  Run       Generate CSV      Date               Module Options
  ---------------------------------------------------------------
  acme      (gencsv|-g)       {date_input}
  acme      (gencsv|-g)       {date_input}       {module_options}


  Interface for the utility script. For list of commands, use 'acme util help'!
  -----------------------------------------------------------------------------
  Run       Utility           Input
  --------------------------------------------------------
  acme      (utility|util)    (arg1)      (arg2)    etc..
  acme      (utility|util)    (help|-h)
  acme      (utility|util)    (man)


  Run       Help Manual & About
  -----------------------------
  acme      man
  acme      (help|--help|-h)
  acme      (--version|-v)


"""

# Usage
#
# 1. Navigate to the parent of your `logs` directory. For example:
#
#      cd  ~/Documents/Metrics/
#
# 2. Use the acme command. Examples:
#
#      acme
#      acme  stats
#      acme  list-files
#      acme  today
#      acme  1/1
#      acme  1/1/2024
#      acme  gencsv today
#      acme  util makefiles
#
# Note: By default, acme will look for `./logs/` in the current working directory and parent directories.

import os
import sys
import analyze

logs_name = 'logs'
gen_name  = 'gen'
app_name  = 'app'


def find_path(name):
  """Checks if directory (name) exists in current or parents"""

  curr = os.path.abspath(os.curdir)
  
  while True:
    search_path = os.path.join(curr, name)
    if os.path.isdir(search_path):
      return search_path
    
    par = os.path.dirname(curr)
    
    if curr == par:
      return None
    
    curr = par


def main():

  find_logs = find_path(logs_name)

  if find_logs:

    parent    = os.path.dirname(find_logs)
    logs_dir  = f'{parent}/{logs_name}/'
    gen_dir   = f'{parent}/{gen_name}/'
    app_dir   = f'{parent}/{app_name}/'

    analyze.analyze(sys.argv[1:], sys.argv[0], { 
      'version'   : v, 
      'copyright' : c, 
      'manual'    : man,
      'logs_dir'  : logs_dir,
      'gen_dir'   : gen_dir,
      'app_dir'   : app_dir,
    })

  else:

    print(f'Logs directory `{logs_name}` not found.')


if __name__ == '__main__':
  main()


