#!/usr/bin/env bash

help=$(cat <<-END

Bash helper to create date files and month directories.

Usage:

  Helper     Command     Parent  Apply/Run
  ----------------------------------------
  ./helper   makefiles   dir/
  ./helper   makedirs    dir/
  ./helper   makefiles   dir/    apply
  ./helper   makedirs    dir/    apply
 
END
)


com=$1
dir="${2:-./}"
apply=$3

if [ "$com" = "makefiles" ]; then

  if [ "$apply" = "apply" ]; then
    echo "Applying making files in $dir"
    for i in {1..31}; do if [ $i -lt "10" ]; then i="0$i"; fi; touch "$dir$i.txt" && echo "touch $dir$i.txt applied"; done
  else
    echo "Mock-making files in $dir"
    for i in {1..31}; do if [ $i -lt "10" ]; then i="0$i"; fi; echo "touch $dir$i.txt"; done
  fi

elif [ "$com" = "makedirs" ]; then

  if [ "$apply" = "apply" ]; then
    echo "Applying making dirs in $dir"
    for i in {1..12}; do if [ $i -lt "10" ]; then i="0$i"; fi; mkdir "$dir$i" && echo "mkdir $dir$i applied"; done
  else
    echo "Mock-making dirs in $dir"
    for i in {1..12}; do if [ $i -lt "10" ]; then i="0$i"; fi; echo "mkdir $dir$i"; done
  fi

elif [ "$com" = "help" ] || [ "$com" = "-h" ]; then
  echo "$help"

else
  echo "Use the help or -h command for proper usage."

fi


